Tilføjede check for user med særlige rettigheder
CodingPirates/forenings_medlemmer pull request #1030
Opened 2024-04-12 06:57 UTC by mhewel

Tilføjede check for user med særlige rettigheder:
"members.view_all_departments"
"members.view_all_unions

2024-04-14 15:52 UTC, rasmusselsmark approved these changes
Ser ok ud med mig, så SEK har adgang til disse filtre

2024-05-06 19:43 UTC, lakridserne requested changes

2024-05-06 19:43 UTC, lakridserne commented on members/admin/inlines.py
> -            return qs
De hjer 2 linjer skal ikke slettes

2024-05-06 19:46 UTC, lakridserne approved these changes

2024-05-06 19:48 UTC, merged