Datofix
CodingPirates/forenings_medlemmer pull request #684
Opened 2021-06-16 23:35 UTC by benj5378

Skal jeg være helt seriøst, så tog det 3-4 timer at læse dokumentationen for crispy forms igennem, så tilbage til Django model.forms, so django.forms.fields og så tilbage til crispy forms igen. Anyways, nyd de 19 anslags rettelse... til en stykpris af 10 minutter.

Fixer #674

2021-06-17 04:53 UTC, lakridserne commented
Du mangler i hvert fald lige at køre Black.

2021-06-19 14:08 UTC, JakobLibak requested changes
Glimrende, hvis du kan få det samlet på een linje. Så tester jeg gerne.

2021-08-08 19:27 UTC, JakobLibak commented
@Rotendahl @lakridserne Hvad mangler for at kunne merge denne?

2022-04-27 06:43 UTC, falle1234 commented
Jeg har tjekket ændringerne til dette PR ud på min lokale master, og har testet at fødselsdato kommer med ud. 
Der er heller ikke problemer med hverken Black eller Flake8.
Jeg giver det gerne et skud i forhold til at skrive en test, hvis det blokerer for at rettelsen kan merges ind.
Ellers bør den kunne merges og lukkes.

Sig endelig til, hvis jeg har overset noget.

2022-04-27 18:55 UTC, lakridserne approved these changes

2022-04-27 18:56 UTC, merged