Quick form that makes it possible to get an email to a department head
CodingPirates/forenings_medlemmer pull request #689
Opened 2021-06-23 21:50 UTC by lakridserne

Sends an email to department head - so it doesn't need to be a manual process. It's a first step - when we get time, it'll good to get the whole process optimized.

2021-07-31 18:15 UTC, JakobLibak commented
Hej @lakridserne. Du må gerne tilføje en beskrivelse af hvad der er blevet ændret, og hvordan processen er i de nye ændringer. Jeg vil gerne undgå at gætte mig frem ved at læse ændret kode i 10 filer igennem.

2021-07-31 19:12 UTC, lakridserne commented
Hej @JakobLibak 

Det er en simpel formular som du kan se på https://medlemssystem-pr-689.herokuapp.com/volunteer_signup

Når man udfylder den fyrer den en mail af til afdelingskaptajnen.

2021-08-01 21:42 UTC, Rotendahl requested changes
Ser rigtig godt ud! 

Der er en mapping fejl som skal ændres før den kan merges. 
Så gav jeg to syntax ændringsforslag som du kan overveje om du gider. 

Jeg har også kørt `get_live_data` på review appen, mest for at se størrelsen på dropdown. Det kan være vi skal sotere listen udefra navn istedet.  Den er ret stor og måske lidt uoverskuelig, men det er mere @JakobLibak's domæne. 

Lige nu fejler den på testserver fordi den ikke kan finde den email template. 
Men det kan kan jo løses ved at gå ind og oprette den. 

En pænere løsning ville være at skrive det som en data-migration (eller måske en statisk singleton getter). Så kan vi være sikker på den altid eksister. Men nu er det her jo også mere et hyggeprojekt så den hurtige løsning er jo også fin. 

Udover mapping feline ser jeg ikke noget der _skal_ ændres. 
Og den ser forresten også rigtig godt ud på mobil!

2021-08-01 21:42 UTC, Rotendahl commented on members/views/volunteerEmail.py
> +            if vol_email.is_valid():
Igen en lidt ligegyldig ting, men du kan sætte if sætnings sammen så der ikke er tre efter hinanden. Python har short circuit på `and` så den kaster ikke undtagelser hvis det første fejler. Så enten: 
```python
if request.method == "POST" and request.POST["form_id"] == "vol_email":
    vol_email = vol_emailForm(request.POST)
    if vol_email.is_valid():
        ...
```
Efter python 3.8 kan vi også gøre sådan det med "Walrus operator" 
https://docs.python.org/3/whatsnew/3.8.html

```python
if (
 request.method == "POST" 
 and request.POST["form_id"] == "vol_email":
 and (vol_email := vol_emailForm(request.POST)).is_valid()
):
    ...
```
Men det er nok en smagssag hvad man kan lide.

2021-08-09 19:01 UTC, Rotendahl approved these changes

2021-08-09 19:04 UTC, merged