Feature/admin activity overview short descr
CodingPirates/forenings_medlemmer pull request #763
Opened 2022-11-21 11:39 UTC by mhewel

in Activity overview in Admin:
a. changed column header for 3 columns showing total seats, used seats and free seats.
b. shortened activity description to max 100 characters. If it was longer then suffix "[..]"

2022-11-21 12:14 UTC, lakridserne requested changes

2022-11-21 12:14 UTC, lakridserne commented on members/admin/activity_admin.py
> +        "activityDescShort",
I python bruger man mest snake_case. Jeg har ikke en stærk holdning, ud over det skal være konsistent.

2022-11-21 12:38 UTC, rasmusselsmark commented on members/admin/activity_admin.py
> +        "activityDescShort",
enig, lad os holde det konsistent

2022-11-21 12:39 UTC, rasmusselsmark commented on members/admin/activity_admin.py
> +        "activityDescShort",
Så f.eks.
```suggestion
        "description_short",
```
?

2022-11-21 12:40 UTC, rasmusselsmark commented on members/admin/activity_admin.py
> +        "activityDescShort",
Så f.eks.
```suggestion
        "description_short",
```
?

2022-11-21 12:40 UTC, rasmusselsmark commented on members/admin/activity_admin.py
> +        "activityDescShort",
Så f.eks.
```suggestion
        "description_short",
```
?

2022-12-12 20:29 UTC, rasmusselsmark approved these changes
Ser fint ud, gennemgik også online sammen med Mikael

2022-12-12 20:55 UTC, rasmusselsmark commented
`Run tests & Analyse code / Test (push)` er ok, men `pull_request` venter på code coverage. Merger

2022-12-12 20:56 UTC, rasmusselsmark commented
@lakridserne, du skal lige godkende igen, før vi kan merge

2022-12-12 21:12 UTC, lakridserne approved these changes

2022-12-12 21:17 UTC, merged