Rettet betalingsinfo så der er lokal timezone istedet for UTC
CodingPirates/forenings_medlemmer pull request #782
Opened 2022-12-26 10:42 UTC by mhewel

Lavet utc_to_local_ymdhm funktion der nu bruges til konverting af betalings info timestamps

2022-12-26 11:56 UTC, rasmusselsmark commented
Siden `pytz` er et Python module, tænker jeg ikke `package-lock.json` skal opdateres (er til Node.js pakker). Skal den til gengæld tilføjes til `poetry.lock`?

Vi skal i hvert fald lige have deployet til test, så vi er sikker på at docker kan bygges.

2022-12-26 12:19 UTC, mhewel commented
Der er ikke problemer på min test her (under poetry)
Den fejler på GitHub ifm test

2022-12-26 13:00 UTC, rasmusselsmark commented
> Der er ikke problemer på min test her (under poetry) Den fejler på GitHub ifm test

Github test fejler med
```
ModuleNotFoundError: No module named 'pytz'
```
Vil tro du skal køre en `poetry add pytz` lokalt?

"Works on my machine" er ikke godt nok, beklager 😀

2022-12-29 09:04 UTC, lakridserne requested changes
Sørg lige for at lade være med at fjerne poetry.lock

2022-12-29 09:27 UTC, lakridserne approved these changes

2022-12-29 12:42 UTC, lakridserne approved these changes

2022-12-29 15:39 UTC, rasmusselsmark approved these changes
Reviewet med Mikael

2022-12-29 15:40 UTC, merged