Vis kun forening hvis det er for medlemskab, og skjul info
CodingPirates/forenings_medlemmer pull request #803
Opened 2023-01-04 09:01 UTC by mhewel

Vis kun forening hvis det er for medlemskab (i Aktiviteter og Deltagere), og skjul foreningsinfo i "Ret aktivitet"

2023-01-06 16:03 UTC, mhewel commented
Nu er informationen om "membership union" kun synlig for super admins

2023-06-18 08:29 UTC, lakridserne requested changes

2023-06-18 08:29 UTC, lakridserne commented on members/admin/activity_admin.py
> +        #            return obj.union
Det der gør ondt i øjnene

2023-06-18 08:29 UTC, lakridserne commented on members/admin/activityparticipant_admin.py
>              return "Andet"
I stedet for alt det her logik, hvis vi skal have Andet, kan vi så ikke defineret andet som den enum det er?

Altså definere det som OT eller noget i den stil

2023-06-18 13:25 UTC, lakridserne approved these changes

2023-06-18 13:40 UTC, merged