Deltagerlisten vist for aktiviteten (i Admin) indeholder nu også besked til arrangør, fototilladelse og betalingsinfo
CodingPirates/forenings_medlemmer pull request #920
Opened 2023-06-21 09:22 UTC by mhewel

eksempel:
![Screenshot_20230621_103308](https://github.com/CodingPirates/forenings_medlemmer/assets/58829786/f048483a-1374-4670-9d22-38c29eb16c11)

2023-07-10 19:23 UTC, lakridserne requested changes

2023-07-10 19:23 UTC, lakridserne commented on members/models/activityparticipant.py
> +                return "Andet er aftalt"
Vi bør ikke bruge en exception til at returnere en tekst - exceptions bør være håndtering af deciderede fejl.

2023-07-10 19:52 UTC, lakridserne commented
Det vil være lækkert hvis man ikke kan slette deltagere, samt aktiviteter der er deltagere på.

2023-07-12 11:21 UTC, mhewel commented
> Det vil være lækkert hvis man ikke kan slette deltagere, samt aktiviteter der er deltagere på.

Slet checkbox for deltagere er fjernet.
Hvis man trykker på Slet knappen vil den check om der er deltagere / betalinger, og blokere sletning af aktivitet hvis der findes deltager/betalinger

2023-07-12 11:37 UTC, mhewel commented on members/models/activityparticipant.py
> +                return "Andet er aftalt"
payment_info() er ændret, og de steder hvor payment_info() bliver kaldt er også ændret.

2023-08-20 08:39 UTC, rasmusselsmark approved these changes
Gennemgået på Mikaels PC her til fysisk udviklerdag

2023-08-20 09:49 UTC, lakridserne commented on members/models/activityparticipant.py
> +            result_string = f"{html_good_pre}Gratis.{html_post} "
Flyt disse linjer op over try/except (linje 77).

Husk at returnere det, ellers udfører den fortsat det i try/except!

2023-08-20 14:04 UTC, lakridserne approved these changes

2023-08-20 14:05 UTC, merged